### PR TITLE
photos: link higher quality

### PR DESCRIPTION
**Pull request by half-duplex**
Example: https://twitter.com/NASAWebb/status/1545413807996129280
Current: `< Sopel> [Twitter] NASA Webb Telescope (@NASAWebb): 🎯 Target(s) acquired!   ⏎  ⏎ The targets of Webb’s first images have been announced: https://go.nasa.gov/3ysrC73 ⏎  ⏎ ✨ SMACS 0723  ⏎  ⏎ ✨ WASP-96b  ⏎  ⏎ ✨ Southern Ring Nebula  ⏎  ⏎ ✨ Stephan’s Quintet  ⏎  ⏎ ✨ Carina Nebula  ⏎  ⏎ Tune in July 12 as we reveal Webb’s first images & #UnfoldTheUniverse. https://pbs.twimg.com/media/FXJpp-XX0AAhLuj.jpg | 2618 RTs | 10157 ?`

Proposed: `< Sopel> [Twitter] NASA Webb Telescope (@NASAWebb): 🎯 Target(s) acquired!   ⏎  ⏎ The targets of Webb’s first images have been announced: https://go.nasa.gov/3ysrC73 ⏎  ⏎ ✨ SMACS 0723  ⏎  ⏎ ✨ WASP-96b  ⏎  ⏎ ✨ Southern Ring Nebula  ⏎  ⏎ ✨ Stephan’s Quintet  ⏎  ⏎ ✨ Carina Nebula  ⏎  ⏎ Tune in July 12 as we reveal Webb’s first images & #UnfoldTheUniverse. https://pbs.twimg.com/media/FXJpp-XX0AAhLuj.jpg:orig | 2618 RTs | 10`

Note the difference in sizes between https://pbs.twimg.com/media/FXJpp-XX0AAhLuj.jpg and https://pbs.twimg.com/media/FXJpp-XX0AAhLuj.jpg:orig

### CODE REVIEW

**Comment by half-duplex** [comment]
afaik twitter only offers `thumb` up to `large` in explicit metadata

**Comment by dgw** [comment]
Sigh. The other question is, since the purpose of outputting the actual media URLs (rather than whatever gets displayed in the tweet text) is embedded pics in clients like The Lounge: Will `:orig` break that?

@xnaas IIRC you use TL with media previews. Anything we should know?

**Comment by xnaas** [comment]
I've never really had any issue with whatever size it's defaulting to, personally. Nor have any of my users complained about it either.

**Comment by dgw** [comment]
> Make it configurable? 🤪

You joke, but this sort of thing absolutely could be a user/channel preference.

I still don't think that `:orig` is a sensible default for the primary intent: inline previews. If TL is smart enough to figure out that `.jpg:large` or `.jpg:orig` is an image and preview it anyway (even if _only_ media previews are turned on, and not all URLs) than maybe it's worth the effort to implement that as a channel setting.

(My TL doesn't have previews enabled, so I'm deferring to @xnaas' experience in his own big channel(s).)

**Comment by xnaas** [comment]
There exists a problem with "large" (Never™ determined the exact number of bytes where it starts to become and issue) image embeds that is only an issue with The Lounge and iOS specifically, as far as I know.

https://user-images.githubusercontent.com/8271327/178571610-780ac55a-e999-458e-9935-b9f98c7ccd62.MOV

As you can see in the video: `:large` (405.1KiB) has no issues, but things quickly become very fucky with `:orig` (4.4MiB)... 😅 As far as I know this doesn't happen on Android devices and it's just a standard "Apple sucks" affair.

**Comment by half-duplex** [comment]
Changed it to link :large w/ explicit availability check. Worth making configurable? Whole bot, per-channel, both?

**Comment by dgw** [comment]
Hmm, I don't like being the bearer of bad news but this approach won't convert well to API v2 (WIP at #23). Per [the migration guide](https://developer.twitter.com/en/docs/twitter-api/migrate/data-formats/standard-v1-1-to-v2), `sizes` on Media objects isn't really a thing any more. (With apologies, you'll have to <kbd>Ctrl</kbd>+<kbd>F</kbd> for "sizes" because Twitter doesn't include fragment anchors of any kind in their doc pages.)

Mildly off-topic: API v2 seems like a step backward for many use cases, but we don't have much choice except to migrate the code Eventually™. New users are unable to configure this plugin because Twitter no longer offers credentials for v1.1.

**Comment by half-duplex** [comment]
The structures and URLs change, but the information may still be there in a more annoying format.
The first example here has what I would expect, but is for a link preview - infuriatingly there are no examples with photo attachments.
https://developer.twitter.com/en/docs/twitter-api/data-dictionary/example-payloads

**Comment by dgw** [comment]
Since I was logged into my developer account, I left feedback requesting they add an example with Photo type, arguing that those appear to be more common than videos.

Meanwhile, consult the Media object model: https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/media

**Comment by dgw** [comment]
Abandoning this; see #40. If the sky miraculously doesn't cave in on us after all, we can reopen.

**Pull request closed without merging**
