### PR TITLE
Switch to BooleanAttribute, req. Sopel 7.1+

### PR DESCRIPTION
**Pull request by half-duplex**
- ~Remove unnecessary futures~
- ~Remove coding~
- Update Sopel version dep
- Switch to BooleanAttribute, now that it works :wink:

### CODE REVIEW

**Comment by dgw** [comment]
Sopel 7.1 is **not** py3.6+ only.

**Comment by half-duplex** [comment]
feh. I was thinking of the current development cycle of 8, where we're currently writing 3.6+ code, forgetting plugins aren't on the same cycle.

**Comment by dgw** [comment]
That, incidentally, is why sopel-irc/sopel#2164 will be included in the next 7.1.x maintenance release. No reason to force plugin updates just to avoid this single warning, when 8.0 is going to start warning about a lot more things.

**Comment by dgw** [comment]
I've punted this to the next minor version, since it feels icky to drop support for stuff in a patch version. We're doing the same with `sopel-github`: releasing the bumped Sopel requirement in a minor version (also 0.5.0, by coincidence).

**Pull request merged**
