### PR TITLE
Use tweepy to simplify sopel-twitter and add features

### PR DESCRIPTION
**Pull request by freeboson**
Overview of changes:
- Dropped dependencies on oauth and json
- Added dependency on [tweepy](https://github.com/tweepy/tweepy)
- Config will request access tokens for user auth
- Better handling of twitter URLs
- If twitter URL is for a profile, a summary of the twitter profile is provided
- Tweet text will go beyond the legacy 140 char limit

----

## Maintainers' addendum (mostly @dgw)

Candidates for new PRs:

- [x] Handle profile links (`twitter.com/<name>`), too (done: #7)
- [x] Go beyond 140 characters (done: #4)
- [x] Improve tweet link handling to cover more possibilities seen in the wild
  - Obviously this one will crib a lot from @freeboson's work, but fortunately we have the ability to credit co-authors in commit messages.
- [x] Better error handling (done: #6)

As for why not merge this PR as-is: I don't really want to switch this plugin over to tweepy. That, and @freeboson has been pretty quiet about possibly rebasing/cleaning up the history.

### CODE REVIEW

**Comment by freeboson** [comment]
Note that this includes the functionality of #2.

**Comment by dgw** [comment]
Self-requested review both because I need to go through the changes, and because this needs rebasing for better commit messages. When I do a full review, I'll also push a rebased history somewhere and link to it so @freeboson can :+1: or :-1: my rewritten history.

**Comment by dgw** [comment]
Revised plan (many months later…) is to reimplement The Good Parts™ of this in separate PRs. I'll append a task list to the OP with the specific things I want to keep.

**Comment by dgw** [comment]
Good to go with tweepy-free reimplementations of everything I wanted from this.

**Pull request closed without merging**
